### ISSUE TITLE
Feature: Static HTML/CSS/JS Archive Explorer Packaged Along with Archive Download

### ISSUE THREAD

**Issue by gchartier** [orcfax/explorer.orcfax.io#13]
### What problem are you trying to solve?

When a user downloads an archival package, it may be difficult to make sense of it on its own, which is one of the main benefits of the Orcfax Explorer. However, since we are enabling the downloading of the archive as files in its entirety to the user's machine, it would be very helpful to package along with it a static HTML/CSS/JS "viewer" of those files that looks and feels like the hosted Orcfax Explorer web app.

### Describe the solution you’d like

A static HTML/CSS/JS "viewer" interface that shows basic information about:
    - The feed this FS archive is for
    - The Fact Statement it is for
    - A breakdown of the contents of the archive
    - A file explorer of the archive contents like the one on the explorer currently

**Comment by ross-spencer** [comment]
This is a cool feature that's probably worth having for the sake of it, and especially if it's low-effort high impact. I am wondering though does the conversation need to be had in light of the storage/IPLD conversation in case the concept for Orcfax's audit package changes?

**Comment by ross-spencer** [comment]
Really nice. Looking forward to seeing this!
